services:
  scanomatic:
    privileged: true
    build: .
    ports: ["5000:5000"]
    environment:
      - LOGGING_LEVEL=20
    volumes:
      - ${SOM_SETTINGS:-./.scan-o-matic}:/root/.scan-o-matic
      - ${SOM_PROJECTS_ROOT:-./somprojects}:/somprojects
      - /dev/bus/usb:/dev/bus/usb
