[tox]
requires =
    tox-uv>=1.16.0
envlist = unit,integration,system
isolated_build = true

[testenv]
basepython = python3.9

[testenv:unit]
extras = test
commands =
    python -m pytest \
        --cov scanomatic --cov scripts --cov-report xml \
        --junitxml result.xml --ignore dev \
        {posargs} tests/unit

[testenv:integration]
extras = test
commands =
    pytest \
        --cov scanomatic --cov scripts --cov-report xml \
        --junitxml result.xml --ignore dev \
        {posargs} tests/integration

[testenv:system]
extras = test
whitelist_externals =
    chromedriver
    geckodriver
passenv =
    DISPLAY
    XAUTHORITY
commands =
    pytest \
        --ignore dev \
        {posargs} tests/system

[testenv:mypy]
sitepackages = False
extras = test,typecheck
commands =
    mypy \
        --check-untyped-defs --warn-unused-ignores --no-incremental \
        scanomatic tests

[testenv:lint]
extras = lint
commands =
    flake8

[flake8]
max_line_length = 80
extend_exclude = node_modules,.venv,.tox

[mypy]
plugins = numpy.typing.mypy_plugin
