[tox]
envlist = py39,unit,integration,system,mypy,lint
skipsdist = true

[testenv:unit]
basepython = python3.9
deps =
    -rrequirements.txt
    mock==4.0.3
    pytest==7.2.0
    pytest-cov==4.0.0
    pytest-flask==1.2.0
commands =
    python -m pytest \
        --cov scanomatic --cov scripts --cov-report xml \
        --junitxml result.xml --ignore dev \
        {posargs} tests/unit

[testenv:integration]
basepython = python3.9
deps =
    -rrequirements.txt
    mock==4.0.3
    pytest==7.2.0
    pytest-cov==4.0.0
    pytest-flask==1.2.0
commands =
    pytest \
        --cov scanomatic --cov scripts --cov-report xml \
        --junitxml result.xml --ignore dev \
        {posargs} tests/integration

[testenv:system]
basepython = python3.9
deps =
    -rrequirements.txt
    mock==4.0.3
    pytest==7.2.0
    pytest-docker<3.0.0
    pytest-flask==1.2.0
    selenium==4.6.0
whitelist_externals =
    chromedriver
    geckodriver
passenv =
    DISPLAY
    XAUTHORITY
commands =
    pytest \
        --ignore dev \
        {posargs} tests/system

[testenv:mypy]
basepython = python3.9
sitepackages = False
deps =
    -rrequirements.txt
    mock==4.0.3
    pytest==7.2.0
    pytest-cov==4.0.0
    pytest-docker<3.0.0
    pytest-flask==1.2.0
    mypy==0.990
    selenium==4.6.0
commands =
    mypy \
        --check-untyped-defs --warn-unused-ignores --no-incremental \
        scanomatic tests

[testenv:lint]
basepython = python3.9
deps =
    flake8==5.0.4
commands =
    flake8

[flake8]
max_line_length = 80
extend_exclude = node_modules,.venv,.tox

[mypy]
plugins = numpy.typing.mypy_plugin
